[project]
name = "azure-keyvault-demo"
version = "0.1.0"
description = "Azure Key Vault Python Demo"
requires-python = ">=3.8"
dependencies = [
    "azure-identity>=1.14.0",
    "azure-keyvault-secrets>=4.8.0,<=4.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
